### ISSUE TITLE
Might fail because of missing Compat

### ISSUE THREAD

**Issue by andreasnoack** [NHDaly/ApplicationBuilder.jl#32]
This code https://github.com/NHDaly/ApplicationBuilder.jl/blob/8bb5f60b2e408e08674431d5e6461be77e317b1a/src/ApplicationBuilder.jl#L156-L169 might fail because nothing ensures that `Compat` is available when the code is run by `PackageCompiler`. That was indeed the case for me. Maybe this can be fixed with
```julia
using ApplicationBuilder: Compat
```
instead. However, `PackageCompiler` doesn't pass the project file information to the subprocess so it might also be the case that my suggested solution fails.

**Comment by NHDaly** [comment]
👍  Thanks, great catch!

I think I need to just make a clean break from pre 0.7 releases and tag a new release! I haven't  updated ApplicationBuilder in a while, but i'm starting to get back around to it.

**Comment by NHDaly** [comment]
:) Thanks!

I've just gone ahead and dropped 0.6 support, and Compat along with it. :) Lemme know if I missed anything!
