### ISSUE TITLE
Application destination directory and name

### ISSUE THREAD

**Issue by Astrych** [NHDaly/ApplicationBuilder.jl#42]
Why application on Linux is packaged into additional `appname/core` directories and why application binary name is not `appname` but the name of Julia file containing julia_main function? I think it makes sense for MacOS platform but not so much on Linux/Windows.

Why the `builddir` directory is put inside the same directory julia_main function file is located? For example build_app_bundle executed like this:
```julia
build_app_bundle("src/App.jl", appname="app", builddir="build")
```
put `build` directory inside `src` one which is not very intuitive I would say.

**Comment by NHDaly** [comment]
Yeah, if you think that would be better, let's change it! :)

Would you be able to open a PR?

**Comment by Astrych** [comment]
I think I can. Julia is a relatively new language for me but it's fun so I think I will manage :)

**Comment by Astrych** [comment]
Small update: I still plan to do that I was just very busy lately. I think I will be able to look on it this weekend.

**Comment by NHDaly** [comment]
https://github.com/NHDaly/ApplicationBuilder.jl/pull/48/ has addressed all of these concerns! :)

The linux/windows build has been changed to write to `$appname/bin/$binary_name`. The `binary_name` defaults to your script's basename, but can be changed via a flag. 
https://github.com/NHDaly/ApplicationBuilder.jl/blob/896e541a08d06a237124eb2ff35643aa080f933f/src/bundle.jl#L10

The buildpath is now understood to be relative to cwd, as paths usually are on the command line:
https://github.com/NHDaly/ApplicationBuilder.jl/blob/896e541a08d06a237124eb2ff35643aa080f933f/src/bundle.jl#L19-L21
https://github.com/NHDaly/ApplicationBuilder.jl/pull/48/files#diff-c124f08b6e3c986fc3a10e09702f0f01L13


thanks for bringing up these issues @Astrych! :)

**Comment by NHDaly** [comment]
(I'm next going to unify the mac and linux/windows codebases in https://github.com/NHDaly/ApplicationBuilder.jl/pull/51)

**Comment by Astrych** [comment]
@NHDaly Oh. I forgot about that issue XD Sorry. Great that you have fixed it!

**Comment by NHDaly** [comment]
Haha me too tbh. Until I needed to start building for Linux. ;) Thanks!
Nathan.
