### ISSUE TITLE
Register version 0.4.0

### ISSUE THREAD

**Issue by NHDaly** [NHDaly/ApplicationBuilder.jl#49]
@JuliaRegistrator register()

**Comment by nkottary** [comment]
The above comment is somehow ending with `\r\n\r\n` and Registrator is rejecting it. This is a bug in Registrator, it should trim the string.

But I'm not sure whats causing those extra characters to get input from your browser. Are you using a different OS/browser now?

**Comment by NHDaly** [comment]
I'll give this another shot! :)

**Comment by NHDaly** [comment]
@JuliaRegistrator register()

**Comment by NHDaly** [comment]
:) Thanks for the quick reply and for diagnosing the problem, @nkottary! :) I'm excited to be making the switch to `.toml` files finally!! :)
