### ISSUE TITLE
JuliaCon 2018 talk?

### ISSUE THREAD

**Issue by NHDaly** [NHDaly/ApplicationBuilder.jl#6]
@ranjanan: I'm thinking about doing a talk at JuliaCon about this! I think there are many people who would be interested, and it could be useful!

I think I want it to be an interactive tutorial where we have the audience build their own tiny application.

I've written a draft proposal here:
https://docs.google.com/document/d/1gloLBKCgAj0DFnRR68CC7QchefDAZ0rUJgqvenQN-Ls/edit?usp=sharing

If you get time, would you look it over and let me know what you think? Thanks so much!! :)

**Comment by NHDaly** [comment]
If it is to be interactively, we will probably have to have windows and linux support nailed down by then. But that doesn't seem to hard, and I'd like to have that done by then anyway!!

**Comment by ranjanan** [comment]
Hey, I think it's a great idea. I shall send that PR soon. Really sorry about not doing it earlier.

**Comment by NHDaly** [comment]
(Oops, sorry, i added Comment access on the google doc link. Thanks for taking a look!)

If you think it looks okay, i'll submit it tonight! :)

**Comment by NHDaly** [comment]
Okay cool I'm gonna submit this then within the hour! Thanks again!

**Comment by ranjanan** [comment]
Hi Nathan,

I think it looks great otherwise. Go for it! :)

Best,
Ranjan

**Comment by NHDaly** [comment]
Thanks! Submitted! Haha oh, i just realized you can edit it afterwards anyway. :) Thanks again though!
