### ISSUE TITLE
unsupported keyword argument "verbose"  :/

### ISSUE THREAD

**Issue by programistawpf** [NHDaly/ApplicationBuilder.jl#60]
julia> build_app_bundle("hello.jl", appname="HelloWorld", verbose=true)
ERROR: MethodError: no method matching build_app_bundle(::String; appname="HelloWorld", verbose=true)
Closest candidates are:
  build_app_bundle(::String; resources, libraries, builddir, appname, create_installer) at C:\Users\PC\.julia\pa
ckages\ApplicationBuilder\PzBv2\src\bundle.jl:13 got unsupported keyword argument "verbose"
Stacktrace:
 [1] kwerr(::NamedTuple{(:appname, :verbose),Tuple{String,Bool}}, ::Function, ::String) at .\error.jl:97
 [2] (::getfield(ApplicationBuilder, Symbol("#kw##build_app_bundle")))(::NamedTuple{(:appname, :verbose),Tuple{S
tring,Bool}}, ::typeof(build_app_bundle), ::String) at .\none:0
 [3] top-level scope at none:0

julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)

julia> readlines("hello.jl")
12-element Array{String,1}:
 "# Create a temporary .html file, and open it to share the greetings."

 "Base.@ccallable function julia_main(ARGS::Vector{String})::Cint"

 "    tmpdir = mktempdir()"

 "    filename = joinpath(tmpdir, \"hello.html\")"

 "    open(filename, \"w\") do io"

 "        println(io, \"Hello, World!\")"

 "        println(io, \"<br>    -- Love, \$PROGRAM_FILE\")"

 "        println(io, \"\"\"<br><br>Current working directory: <a href=\"file://\$(pwd())\">\$(pwd())</a>\"\"\")
"
 "    end"

 "    run(`open file://\$filename`)"

 "    return 0"

 "end"

**Comment by NHDaly** [comment]
This should be fixed now! :) Thanks for the error report!
